export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "",
      "prop": "id"
    },	  {
      "type": "input",
      "label": "审批类型",
      "prop": "type"
    },	  {
      "type": "input",
      "label": "审批码",
      "prop": "auditId"
    },	  {
      "type": "input",
      "label": "审核状态：1：审核中；2：审核通过；3：审核未通过",
      "prop": "status"
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime"
    },	  {
      "type": "input",
      "label": "结束时间",
      "prop": "endTime"
    },	  {
      "type": "input",
      "label": "创建人",
      "prop": "createBy"
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "remark"
    },	  {
      "type": "input",
      "label": "最后更新时间",
      "prop": "updateTime"
    },	  {
      "type": "input",
      "label": "结果消息",
      "prop": "resultMsg"
    }  ]
}
