export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "dialogDirection": "rtl",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id"
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime"
    },	  {
      "type": "input",
      "label": "创建人",
      "prop": "createBy"
    },	  {
      "type": "input",
      "label": "修改时间",
      "prop": "updateTime"
    },	  {
      "type": "input",
      "label": "修改人",
      "prop": "updateBy"
    },	  {
      "type": "input",
      "label": "逻辑删除标记",
      "prop": "enable"
    },	  {
      "type": "input",
      "label": "排序号",
      "prop": "sort"
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "remark"
    },	  {
      "type": "input",
      "label": "商铺id",
      "prop": "coreShop"
    },	  {
      "type": "input",
      "label": "储值卡名称",
      "prop": "name"
    },	  {
      "type": "input",
      "label": "图片",
      "prop": "image"
    },	  {
      "type": "input",
      "label": "面额",
      "prop": "money"
    },	  {
      "type": "input",
      "label": "价格",
      "prop": "price"
    },	  {
      "type": "input",
      "label": "会员等级关联",
      "prop": "level"
    },	  {
      "type": "input",
      "label": "是否开启会员储值（1.开启2.关闭）",
      "prop": "isOpen"
    },	  {
      "type": "input",
      "label": "是否可以任意充值(1.开启2.关闭)",
      "prop": "isRandomTopup"
    },	  {
      "type": "input",
      "label": "最低充值金额",
      "prop": "minTopup"
    },	  {
      "type": "input",
      "label": "状态（1.销售中2.暂停销售）",
      "prop": "status"
    }  ]
}
