export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "dialogDirection": "rtl",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id"
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime"
    },	  {
      "type": "input",
      "label": "创建人",
      "prop": "createBy"
    },	  {
      "type": "input",
      "label": "修改时间",
      "prop": "updateTime"
    },	  {
      "type": "input",
      "label": "修改人",
      "prop": "updateBy"
    },	  {
      "type": "input",
      "label": "逻辑删除标记",
      "prop": "enable"
    },	  {
      "type": "input",
      "label": "排序号",
      "prop": "sort"
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "remark"
    },	  {
      "type": "input",
      "label": "商铺用户id",
      "prop": "shopUser"
    },	  {
      "type": "input",
      "label": "店铺剧本id/储值卡id/商品id",
      "prop": "goodId"
    },	  {
      "type": "input",
      "label": "实际价格",
      "prop": "pricing"
    },	  {
      "type": "input",
      "label": "实付价格",
      "prop": "realPay"
    },	  {
      "type": "input",
      "label": "付款状态（1.未付款2.已付款）",
      "prop": "status"
    },	  {
      "type": "input",
      "label": "支付方式（1.余额2.微信）",
      "prop": "payType"
    },	  {
      "type": "input",
      "label": "订单类型（1.剧本组团付费2.购买储值卡3.购买商品）",
      "prop": "orderType"
    }  ]
}
