export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "dialogDirection": "rtl",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "ID",
      "prop": "id"
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime"
    },	  {
      "type": "input",
      "label": "创建人",
      "prop": "createBy"
    },	  {
      "type": "input",
      "label": "修改时间",
      "prop": "updateTime"
    },	  {
      "type": "input",
      "label": "修改人",
      "prop": "updateBy"
    },	  {
      "type": "input",
      "label": "逻辑删除标记",
      "prop": "enable"
    },	  {
      "type": "input",
      "label": "排序号",
      "prop": "sort"
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "remark"
    },	  {
      "type": "input",
      "label": "等级名称",
      "prop": "name"
    },	  {
      "type": "input",
      "label": "折扣",
      "prop": "discount"
    },	  {
      "type": "input",
      "label": "等级",
      "prop": "level"
    },	  {
      "type": "input",
      "label": "积分",
      "prop": "integral"
    },	  {
      "type": "input",
      "label": "图标",
      "prop": "image"
    },	  {
      "type": "input",
      "label": "商铺id",
      "prop": "coreShop"
    }  ]
}
