export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "dialogDirection": "rtl",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "",
      "prop": "id"
    },	  {
      "type": "input",
      "label": "剧本id",
      "prop": "did"
    },	  {
      "type": "input",
      "label": "角色名称",
      "prop": "name"
    },	  {
      "type": "input",
      "label": "角色描述",
      "prop": "detail"
    },	  {
      "type": "input",
      "label": "角色图片",
      "prop": "image"
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime"
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime"
    },	  {
      "type": "input",
      "label": "创建人",
      "prop": "createBy"
    },	  {
      "type": "input",
      "label": "修改人",
      "prop": "updateBy"
    },	  {
      "type": "input",
      "label": "逻辑删除标记",
      "prop": "enable"
    },	  {
      "type": "input",
      "label": "排序号",
      "prop": "sort"
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "remark"
    }  ]
}
