export const tableOption = {
  "border": true,
  "index": true,
  "indexLabel": "序号",
  "stripe": true,
  "menuAlign": "center",
  "align": "center",
  "dialogDirection": "rtl",
  "searchMenuSpan": 6,
  "column": [
	  {
      "type": "input",
      "label": "",
      "prop": "id"
    },	  {
      "type": "input",
      "label": "店铺id",
      "prop": "sid"
    },	  {
      "type": "input",
      "label": "优惠券名称",
      "prop": "title"
    },	  {
      "type": "input",
      "label": "优惠券类型：1-免单券，2-折扣券，3-代金券",
      "prop": "type"
    },	  {
      "type": "input",
      "label": "价格或折扣",
      "prop": "num"
    },	  {
      "type": "input",
      "label": "指定商品id",
      "prop": "gid"
    },	  {
      "type": "input",
      "label": "优惠券状态：0-未发布，1-已发布，2-已下架",
      "prop": "state"
    },	  {
      "type": "input",
      "label": "有效期天，0为永久",
      "prop": "valid"
    },	  {
      "type": "input",
      "label": "领取次数限制",
      "prop": "receive"
    },	  {
      "type": "input",
      "label": "发布总张数，0为不限",
      "prop": "total"
    },	  {
      "type": "input",
      "label": "创建时间",
      "prop": "createTime"
    },	  {
      "type": "input",
      "label": "更新时间",
      "prop": "updateTime"
    },	  {
      "type": "input",
      "label": "创建人",
      "prop": "createBy"
    },	  {
      "type": "input",
      "label": "修改人",
      "prop": "updateBy"
    },	  {
      "type": "input",
      "label": "逻辑删除标记",
      "prop": "enable"
    },	  {
      "type": "input",
      "label": "排序号",
      "prop": "sort"
    },	  {
      "type": "input",
      "label": "备注",
      "prop": "remark"
    }  ]
}
